fixtures:
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    apache: "#{source_dir}"
