language: ruby
sudo: false
cache: bundler

rvm:
  - 2.0.0

script: "bundle exec rake test"

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0"
    - PUPPET_GEM_VERSION="~> 4.0"

notifications:
  email:
    on_failure: change
    on_success: never
